name: ntkd
version: "1.90.1"
summary: Netsukuku daemon
description: Deploy a Netsukuku network!
grade: devel
confinement: devmode

parts:
  ntkd-common:
    source: https://github.com/lukisi/ntkd-common.git
    plugin: autotools
    build-packages:
      - valac
  tasklet-system:
    source: https://github.com/lukisi/tasklet-system.git
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
    stage-packages:
      - libgee-0.8-2
  pth-tasklet:
    source: https://github.com/lukisi/pth-tasklet.git
    after: [tasklet-system]
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
      - libpth-dev
    stage-packages:
      - libgee-0.8-2
      - libpth20
  zcd:
    source: https://github.com/lukisi/zcd.git
    after: [tasklet-system, pth-tasklet]
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
      - libjson-glib-dev
    stage-packages:
      - libgee-0.8-2
      - libjson-glib-1.0-0
  ntkdrpc:
    source: https://github.com/lukisi/ntkdrpc.git
    after: [tasklet-system, zcd]
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
      - libjson-glib-dev
    stage-packages:
      - libgee-0.8-2
      - libjson-glib-1.0-0
  peerservices:
    source: https://github.com/lukisi/peerservices.git
    after: [tasklet-system, pth-tasklet, ntkd-common, ntkdrpc]
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
      - libjson-glib-dev
    stage-packages:
      - libgee-0.8-2
      - libjson-glib-1.0-0
  ntkd:
    source: https://github.com/lukisi/ntkd.git
    after: [tasklet-system, pth-tasklet, ntkd-common, ntkdrpc, peerservices]
    plugin: autotools
    build-packages:
      - valac
      - libgee-0.8-dev
      - libjson-glib-dev
    stage-packages:
      - libgee-0.8-2
      - libjson-glib-1.0-0

apps:
  ntkd:
    command: bin/ntkd

